import type { Metadata } from "next";
import { Noto_Sans_JP } from "next/font/google";

import Header from "@/components/layouts/Header";
import Providers from "@/libs/providers/Providers";
import Auth from "@/libs/Auth";

const notoSansJP = Noto_Sans_JP({
    subsets: ["latin"],
    variable: "--font-noto-sans-jp",
});

export const metadata: Metadata = {
    title: "Tripia",
    description: "Generated by create next app",
};

export default function RootLayout({
    children,
}: Readonly<{
    children: React.ReactNode;
}>) {
    return (
        <html lang="ja">
            <body className={notoSansJP.className}>
                <Auth>
                    <Providers>
                        <Header />
                        {children}
                    </Providers>
                </Auth>
            </body>
        </html>
    );
}
