services:
  app:
    container_name: tripia_app
    build: .
    ports:
      - "8080:8080"
    volumes:
      - .:/app
    command: npm run dev
  db:
    # build:
    #   context: .
    #   dockerfile: ./docker/db/Dockerfile
    image: postgres:17.2
    container_name: tripia_db
    environment:
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - POSTGRES_DB=${POSTGRES_DB}
      - POSTGRES_INITDB_ARGS=${POSTGRES_INITDB_ARGS}
    ports:
      - "5432:5432"
    volumes:
      - postgres_volume:/var/lib/postgresql/data
volumes:
  postgres_volume:
